# Denne er ikke helt korrekt

'### Global parameters
[global]
# workgroup/domain samba server will be a part of
  realm = AD.ANDORAARKITEKTER.NO
  workgroup = AD
  security = ADS
  server role = member server
  kerberos method = secrets and keytab
  name resolve order = host
  dedicated keytab file = /etc/krb5.keytab

# Winbind
  winbind use default domain = yes
  winbind enum users = yes
  winbind enum groups = yes
  winbind refresh tickets = yes

# Ingen hjemmemappe for AD-bruker
template homedir = /nonexistent
# Ikke logge inn i terminal
template shell = /bin/false


winbind refresh tickets = Yes
vfs objects = acl_xattr
map acl inherit = Yes
store dos attributes = Yes

# Defaults for winbind
  idmap config * : backend = tdb
  idmap config * : range = 3000-7999

  idmap config AD : backend = rid
  idmap config AD : range = 10000-999999

# Allow users who've been granted usershare priveleges to create public shares, not just authenticated ones
  usershare allow guests = yes

[felles]
path = /srv/shares/felles
browseable = yes
read only = no
guest ok = no
valid users = @"domain users"
force group = "domain users"
create mask = 0664
directory mask = 2775
