---
# Basekonfigurasjoner alle servere skal ha

- name: Configure basic settings for all servers
  hosts: all
  become: true


# Alle hosts må ha python installert for at Ansible skal kunne utføre playbooks
# For å installere python så må det gjøres som raw? siden ansible ikke kan gjøre noe uten python først.
  tasks:
  - name: Install python
    ansible.builtin.apt:
      name: Python3
      state: present
  
  - name: Turn on unattended upgrades

  - name: Set timezone

  
    

# Slå på NTP
# Sett tidssone
# Slå på unattended upgrades
# Kanskje se på iptablesscriptet jeg hadde for opprettelse av mapper og bakcup osv
# persistent iptables, lag egen fil, deaktivert cloud