---
# Basekonfigurasjoner alle servere skal ha

- name: Configure basic settings for all servers
  hosts: all
  become: true

# Slå på NTP
# Sett tidssone
# Slå på unattended upgrades
# Kanskje se på iptablesscriptet jeg hadde for opprettelse av mapper og bakcup osv
# persistent iptables, lag egen fil, deaktivert cloud