---
# This playbook readys the backupserver for borg initialization
- name: Create user and folders for Borg
  hosts: backupserver
  become: true

  tasks:
    - name: Create backupuser on backupserver
      ansible.builtin.user:
        name: "{{ backup_user }}"
        home: /srv/backup
        shell: /bin/bash/
        create_home: true
        state: present

    - name: Create directory and set backupuser as owner
      ansible.builtin.file:
        path: /srv/backup/borg-repo
        state: directory
        owner: "{{ backup_user }}"
        group: "{{ backup_user }}"
        mode: "0700"