---
# This playbook installs iptables-resisten to persist firewall rules across reboots

- name: Install iptables-persistent
  hosts: all
  become: true

  tasks:
    - name: Prevent install dialog iptables-persistent
      ansible.builtin.debconf:
        name: iptables-persistent
        question: "{{ item }}"
        vtype: boolean
        value: "true"
      loop:
        - iptables-persistent/autosave_v4
        - iptables-persistent/autosave_v6

    - name: Install iptables-persistent
      ansible.builtin.apt:
        name: iptables-persistent
        state: present