---
- name: Installer samba avhengigheter for AD-integrasjon
  hosts: test_servers
  become: true

  tasks:
    - name: Installer winbind, Kerberos og samba
      ansible.builtin.apt:
        name:
          - winbind
          - libnss-winbind
          - libpam-winbind
          - krb5-user
          - samba
        state: present


  # Samba muliggjør fildeling med windows
        # name: samba
        # state: present
        # update_cache: true
        # Eventuelt opprette standard delingsmappe samtidig?
        # Andre playbooks har også enable/start og open firewall
        # Lag egen playbook for samba shares heller tror jeg

  # winbind lar linux og AD snakke sammen
    # - name: Installer winbind
    #   ansible.builtin.apt:
# libnss gjør AD-brukere synlige i Linux
    # - name: installer libnss-winbind
    #   ansible.builtin.apt:
    #     name: libnss-winbind
    #     state: present

# libpam lar AD-brukere logge inn
    # - name: installer libpam-winbind
    #   ansible.builtin.apt:
    #     name: libpam-winbind
    #     state: present

# Kerberos er autentiseringssystemet for AD
    # - name: installer krb5-user
    #   ansible.builtin.apt:
    #     name: krb5-user
    #     state: present
