---
- name: Installer samba avhengigheter for AD-integrasjon
  hosts: samba_fileshare
  become: true

  tasks:
    - name: Installer winbind, Kerberos og samba
      ansible.builtin.apt:
        name:
          - samba
          - winbind
          - libnss-winbind
          - libpam-winbind
          - krb5-user
        state: present
        update_cache: yes


# Samba muliggjør fildeling med windows
# winbind lar linux og AD snakke sammen
# libnss gjør AD-brukere synlige i Linux
# libpam lar AD-brukere logge inn
# Kerberos er autentiseringssystemet for AD
