---
# Run set-fqdn playbook before this one
# This playbook should only be run once on completely new fileshare servers
# Run with --ask-vault-pass

- name: Samba fileserver and join domain
  hosts: new_fileshares
  become: true
  gather_facts: false

  vars_files:
    - ../vars/secrets.yml

  tasks:
    - name: Stop winbind before configurations
      ansible.builtin.service:
        name: winbind
        state: stopped
      failed_when: false

    - name: Configure krb5.conf from template
      ansible.builtin.template:
        src: ../templates/krb5.conf.j2
        dest: /etc/krb5.conf

    - name: Configure smb.conf from template
      ansible.builtin.template:
        src: ../templates/smb.conf.j2
        dest: /etc/samba/smb.conf

    - name: Restart smbd after configuration
      ansible.builtin.services:
        name: smbd
        state: restarted
        enabled: true

    - name: Check if a domain is already joined
      ansible.builtin.command: net ads testjoin
      register: testjoin_output
      changed_when: false
      failed_when: false

    - name: Join domain if not already joined
      ansible.builtin.command: net ads join -U {{ domain_user }}%{{ domain_password }}
      when: testjoin_output.rc != 0
      no_log: true

    - name: Start and enable winbind
      ansible.builtin.service:
        name: winbind
        state: started
        enabled: true

    - name: Configure nsswitch.conf from template
      ansible.builtin.template:
        src: ../templates/nsswitch.conf.j2
        dest: /etc/nsswitch.conf
    
    - name: Create shares parent directory
      ansible.builtin.file:
        path: /srv/shares
        state: directory
        owner: root
        group: "domain users"
        mode: '0755'

    - name: Create shared folder
      ansible.builtin.file:
        path: /srv/shares/felles
        state: directory
        owner: root
        group: "domain users"
        mode: '2770'