---
- name: Add new share
  hosts: samba_fileshare
  become: true
  gather_facts: false

  # Run playbook like this: ansible-playbook playbooks/add-share-samba.yml -e "share_name=mappenavn ad_group=ad_gruppenavn"
  # To limit the share to a specific server use --limit, example: --limit trd-fs01
  # For folder names containing spaces the formatting must be like this: "ad_group='Gruppe i AD'"

  tasks:
    - name: Control if required variables are set
      ansible.builtin.fail:
        msg: 'Variables share_name and ad_group must be set: -e "share_name=mappenavn ad_group=ad_gruppenavn"'
      when: share_name is not defined or ad_group is not defined

    - name: Create new folder
      ansible.builtin.file:
        path: /srv/shares/{{ share_name }}
        state: directory
        owner: root
        group: "{{ ad_group }}"
        mode: '2770'

    - name: Add share to smb.conf
      ansible.builtin.blockinfile:
        path: /etc/samba/smb.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ share_name }}"
        block: |
          [{{ share_name }}]
              comment = Mappe for {{ ad_group }}
              path = /srv/shares/{{ share_name }}
              browseable = no
              read only = no
              valid users = @"{{ ad_group }}"
              force group = "{{ ad_group }}"
              create mask = 0664
              directory mask = 2770

    - name: Restart smbd
      ansible.builtin.service:
        name: smbd
        state: restarted