---
- name: Configure timesyncronisation
  hosts: all
  become: true

  tasks:
    - name: Set system timezone to UTC
      community.general.timezone:
        name: "UTC"
  
    - name: Configure timesyncd from template
      ansible.builtin.template:
        src: ../templates/krb5.conf.j2
        dest: /etc/systemd/timesyncd.conf

    - name: Restart and enable timesyncd
      ansible.builtin.service:
        name: systemd-timesyncd
        state: restarted
        enabled: true