---
- name: Samba fileserver and join domain
  hosts: samba_fileshare
  become: true
  gather_facts: false
  vars:
    domain_user: "administrator" # vault or inline
    domain_password: "password" # vault or inline

  tasks:
    - name: Stop winbind before configurations
      ansible.builtin.service:
        name: winbind
        state: stopped
      failed_when: false

    - name: Configure krb5.conf from template
      ansible.builtin.template:
        src: ../templates/krb5.conf.j2
        dest: /etc/krb5.conf

    - name: Configure smb.conf from template
      ansible.builtin.template:
        src: ../templates/smb.conf.j2
        dest: /etc/samba/smb.conf

    - name: Check if a domain is already joined
      ansible.builtin.command: net ads testjoin
      register: testjoin_output
      changed_when: false
      failed_when: false

    - name: Join domain if not already joined
      ansible.builtin.command: net ads join -U {{ domain_user }}%{{ domain_password }}
      when: testjoin_output.rc != 0
      no_log: true

    - name: Start and enable winbind
      ansible.builtin.service:
        name: winbind
        state: started
        enabled: true

    - name: Configure nsswitch.conf from template
      ansible.builtin.template:
        src: ../templates/nsswitch.conf.j2
        dest: /etc/nsswitch.conf
    
    - name: Create shares parent directory
      ansible.builtin.file:
        path: /srv/shares
        state: directory
        owner: root
        group: "domain users"
        # All domain users can read, but not write
        mode: '0755'

    - name: Create shared folder
      ansible.builtin.file:
        path: /srv/shares/felles
        state: directory
        owner: root
        group: "domain users"
        # Access for all domain users
        mode: '2770'