---
- name: Update og Upgrade pakker
  hosts: test_servers
  become: true

  tasks:
    - name: Oppdatere pakkeliste
      ansible.builtin.apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600
    
    - name: Oppgradere pakker
      ansible.builtin.apt: 
        upgrade: yes
        force_apt_get: yes

    - name: Fjerne ubrukte pakker
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes