---
# This playbook updates package list, upgrades installed packages, and removes unused packages and cache

- name: Update and Upgrade packages
  hosts: all
  become: true

  tasks:
    - name: Update package list
      ansible.builtin.apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600
    
    - name: Upgrade installed packages
      ansible.builtin.apt: 
        upgrade: dist
        force_apt_get: yes

    - name: Remove unused packages and cache
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes