---
- name: Update og Upgrade pakker
  hosts: all
  become: true

  tasks:
    - name: Oppdatere pakkeliste
      ansible.builtin.apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600
    
    - name: Oppgradere installerte pakker
      ansible.builtin.apt: 
        upgrade: dist
        force_apt_get: yes

    - name: Fjerne ubrukte pakker og cache
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes

# Forbedringer til vurdering: reboot hvis det er nødvendig noen form for logging.

    # - name: Check if reboot is required
    #   register: reboot_required_file
    #   stat: path=/run/reboot-required

    # - name: Reboot servers if there was a kernel Update
    #   reboot: 
    #     msg: "Rebooting servers because kernel was updated"
    #     connection_timeout: 5
    #     reboot_timeout: 300
    #     pre_reboot_delay: 30
    #     post_reboot_delay: 30
    #     test_command: uptime
    #   when: reboot_required_file.stat.exists